import { createId, getEndOfCurrentMonthKey, getEndOfCurrentWeekKey, getStartOfCurrentMonthKey, getStartOfCurrentWeekKey } from "~/lib/habitquest/utils";
import type {
  Achievement,
  Challenge,
  HabitQuestData,
  LevelUnlock,
  ShopItem,
} from "~/types/habitquest";

function createAchievement(
  key: Achievement["key"],
  title: string,
  description: string,
  category: Achievement["category"],
  icon: string,
  reward: Achievement["reward"],
): Achievement {
  return {
    id: createId("achievement"),
    key,
    title,
    description,
    category,
    icon,
    unlocked: false,
    unlockedAt: null,
    rewardedAt: null,
    reward,
  };
}

function createChallenge(config: Omit<Challenge, "id" | "progress" | "completed" | "claimed" | "startsAt" | "endsAt">): Challenge {
  const isWeekly = config.period === "weekly";

  return {
    ...config,
    id: createId("challenge"),
    progress: 0,
    completed: false,
    claimed: false,
    startsAt: isWeekly ? getStartOfCurrentWeekKey() : getStartOfCurrentMonthKey(),
    endsAt: isWeekly ? getEndOfCurrentWeekKey() : getEndOfCurrentMonthKey(),
  };
}

function createShopItem(item: Omit<ShopItem, "owned">): ShopItem {
  return {
    ...item,
    owned: false,
  };
}

function createLevelUnlock(
  feature: LevelUnlock["feature"],
  requiredLevel: number,
  label: string,
  description: string,
): LevelUnlock {
  return {
    id: createId("unlock"),
    feature,
    requiredLevel,
    label,
    description,
    unlocked: false,
    unlockedAt: null,
  };
}

export function createSeedData(): HabitQuestData {
  const now = new Date().toISOString();

  return {
    habits: [
      {
        id: createId("habit"),
        title: "Morning stretch",
        description: "A five-minute mobility reset before opening anything else.",
        difficulty: "easy",
        recurrence: "daily",
        customDays: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: createId("habit"),
        title: "Deep work sprint",
        description: "One focused 45-minute block on your most important task.",
        difficulty: "hard",
        recurrence: "daily",
        customDays: [],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: createId("habit"),
        title: "Strength training",
        description: "Short session to keep the body in the game.",
        difficulty: "medium",
        recurrence: "custom",
        customDays: [1, 3, 5],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: createId("habit"),
        title: "Journal recap",
        description: "Close the day with a short review and one improvement note.",
        difficulty: "easy",
        recurrence: "daily",
        customDays: [],
        createdAt: now,
        updatedAt: now,
      },
    ],
    completions: [],
    achievements: [
      createAchievement("first-habit-completed", "First Habit Completed", "Take the first clean step into your run.", "beginner", "Spark", { coins: 5, exp: 20 }),
      createAchievement("reach-level-2", "Reach Level 2", "Prove that momentum is real.", "beginner", "Rune", { coins: 5, exp: 30 }),
      createAchievement("seven-day-streak", "7 Day Streak", "Hold the line for a full week.", "streak", "Flame", { coins: 10, exp: 60 }),
      createAchievement("thirty-day-streak", "30 Day Streak", "Build a streak that changes identity, not mood.", "streak", "Inferno", { coins: 25, exp: 200 }),
      createAchievement("complete-50-habits", "Complete 50 Habits", "Stack enough clears to feel the system working.", "completion", "Ledger", { coins: 15, exp: 80 }),
      createAchievement("complete-100-habits", "Complete 100 Habits", "Hit triple digits on completed habits.", "completion", "Relic", { coins: 30, exp: 150 }),
      createAchievement("reach-level-5", "Reach Level 5", "Break into the veteran tier.", "level", "Crown", { coins: 20, exp: 120 }),
      createAchievement("reach-level-10", "Reach Level 10", "Enter the elite progression bracket.", "level", "Astral", { coins: 50, exp: 250 }),
      createAchievement("buy-first-cosmetic", "Buy First Cosmetic", "Spend coins on identity, not just numbers.", "shop", "Mask", { coins: 10, exp: 40 }),
      createAchievement("complete-weekly-challenge", "Complete Weekly Challenge", "Finish your first weekly contract.", "challenge", "Banner", { coins: 20, exp: 100 }),
    ],
    challenges: [
      createChallenge({
        key: "weekly-contract",
        title: "Weekly Contract",
        description: "Complete 15 habits this week.",
        period: "weekly",
        type: "habit-completions",
        target: 15,
        reward: {
          coins: 20,
          exp: 150,
          titleItemId: "title_weekly_vanguard",
        },
      }),
      createChallenge({
        key: "monthly-ascension",
        title: "Monthly Ascension",
        description: "Earn 2000 EXP this month.",
        period: "monthly",
        type: "exp-earned",
        target: 2000,
        reward: {
          coins: 60,
          exp: 400,
          titleItemId: "title_monthly_archon",
        },
      }),
    ],
    shopItems: [
      createShopItem({
        id: "title_beginner",
        name: "Beginner",
        description: "A humble title for a fresh adventurer.",
        category: "title",
        rarity: "common",
        price: 10,
        requiredLevel: 1,
        requiredFeature: "titles",
        preview: "Novice tag",
        exclusive: false,
      }),
      createShopItem({
        id: "title_habit_hunter",
        name: "Habit Hunter",
        description: "For players who treat daily discipline like a hunt.",
        category: "title",
        rarity: "rare",
        price: 30,
        requiredLevel: 2,
        requiredFeature: "titles",
        preview: "Hunter sigil",
        exclusive: false,
      }),
      createShopItem({
        id: "title_discipline_master",
        name: "Discipline Master",
        description: "A title that implies hard-won consistency.",
        category: "title",
        rarity: "epic",
        price: 75,
        requiredLevel: 5,
        requiredFeature: "titles",
        preview: "Master crest",
        exclusive: false,
      }),
      createShopItem({
        id: "title_night_grinder",
        name: "Night Grinder",
        description: "For the late-hour player who still closes quests.",
        category: "title",
        rarity: "epic",
        price: 85,
        requiredLevel: 5,
        requiredFeature: "titles",
        preview: "Lunar badge",
        exclusive: false,
      }),
      createShopItem({
        id: "title_weekly_vanguard",
        name: "Weekly Vanguard",
        description: "Exclusive title earned from clearing a weekly contract.",
        category: "title",
        rarity: "epic",
        price: 0,
        requiredLevel: 3,
        requiredFeature: "titles",
        preview: "Challenge insignia",
        exclusive: true,
      }),
      createShopItem({
        id: "title_monthly_archon",
        name: "Monthly Archon",
        description: "Exclusive title earned from a major monthly climb.",
        category: "title",
        rarity: "legendary",
        price: 0,
        requiredLevel: 7,
        requiredFeature: "titles",
        preview: "Celestial seal",
        exclusive: true,
      }),
      createShopItem({
        id: "frame_bronze",
        name: "Bronze Frame",
        description: "A grounded metallic profile frame.",
        category: "frame",
        rarity: "common",
        price: 20,
        requiredLevel: 5,
        requiredFeature: "profile-frames",
        preview: "Bronze edge",
        exclusive: false,
      }),
      createShopItem({
        id: "frame_neon",
        name: "Neon Frame",
        description: "Reactive cyan border with arcade energy.",
        category: "frame",
        rarity: "rare",
        price: 55,
        requiredLevel: 5,
        requiredFeature: "profile-frames",
        preview: "Neon circuit",
        exclusive: false,
      }),
      createShopItem({
        id: "frame_galaxy",
        name: "Galaxy Frame",
        description: "An animated cosmic frame with deep-space color shifts.",
        category: "frame",
        rarity: "legendary",
        price: 150,
        requiredLevel: 10,
        requiredFeature: "legendary-cosmetics",
        preview: "Stellar ring",
        exclusive: false,
      }),
      createShopItem({
        id: "avatar_knight",
        name: "Knight",
        description: "Classic heavy-armor discipline energy.",
        category: "avatar",
        rarity: "common",
        price: 18,
        requiredLevel: 1,
        requiredFeature: null,
        preview: "K",
        exclusive: false,
      }),
      createShopItem({
        id: "avatar_wizard",
        name: "Wizard",
        description: "A focused strategist with long-form energy.",
        category: "avatar",
        rarity: "rare",
        price: 36,
        requiredLevel: 2,
        requiredFeature: null,
        preview: "W",
        exclusive: false,
      }),
      createShopItem({
        id: "avatar_samurai",
        name: "Samurai",
        description: "Minimalist steel and ruthless follow-through.",
        category: "avatar",
        rarity: "epic",
        price: 80,
        requiredLevel: 5,
        requiredFeature: null,
        preview: "S",
        exclusive: false,
      }),
      createShopItem({
        id: "avatar_cyber_ninja",
        name: "Cyber Ninja",
        description: "Legendary stealth aesthetic for top-tier grinders.",
        category: "avatar",
        rarity: "legendary",
        price: 165,
        requiredLevel: 10,
        requiredFeature: "legendary-cosmetics",
        preview: "CN",
        exclusive: false,
      }),
    ],
    equippedItems: {
      titleItemId: null,
      frameItemId: null,
      avatarItemId: null,
    },
    wallet: {
      totalCoins: 0,
      lifetimeCoinsEarned: 0,
      lifetimeCoinsSpent: 0,
    },
    dailyRewards: {
      lastLoginDate: null,
      claimedDailyLoginDate: null,
      claimedDailyCompletionRewardDate: null,
    },
    levelUnlocks: [
      createLevelUnlock("titles", 2, "Titles", "Unlock title cosmetics and challenge titles."),
      createLevelUnlock("weekly-challenges", 3, "Weekly Challenges", "Activate weekly contract tracking and rewards."),
      createLevelUnlock("profile-frames", 5, "Profile Frames", "Buy and equip profile frame cosmetics."),
      createLevelUnlock("monthly-challenges", 7, "Monthly Challenges", "Open monthly climb challenges and rewards."),
      createLevelUnlock("legendary-cosmetics", 10, "Legendary Cosmetics", "Gain access to legendary avatars, titles, and frames."),
    ],
    userProgress: {
      totalExp: 0,
      level: 1,
      currentStreak: 0,
      bestStreak: 0,
      totalCompletedHabits: 0,
      lastCompletedDate: null,
      expHistory: [],
    },
  };
}
